Update build-spec.yml

diff --git a/build-spec.yml b/build-spec.yml
--- a/build-spec.yml
+++ b/build-spec.yml
@@ -59,13 +59,24 @@ phases:
   build:
     commands:
       - sonar-scanner -Dsonar.projectKey=$PROJECT -Dsonar.sources=. -Dsonar.host.url=$HOST
-      - sleep 5
+      # - sleep 5
+      # - |
+      #   STATUS=$(curl -s "http://audit.loyalty.cxforge.com/api/qualitygates/project_status?projectKey=codepipeline" | jq -r '.projectStatus.status')
+      #   if [ "$STATUS" = "OK" ]; then
+      #     echo "SonarQube Quality Gate passed."
+      #   else
+      #     echo "SonarQube Quality Gate failed. Stopping CodeBuild..."
+      #     exit 1
+      #   fi
       - |
         STATUS=$(curl -s "$HOST/api/qualitygates/project_status?projectKey=$PROJECT" | jq -r '.projectStatus.status')
-        if [ "$STATUS" = "OK" ]; then
+        if [[ "$STATUS" == "ERROR" ]]; then
+          echo "SonarQube Quality Gate failed. Stopping CodeBuild..."
+          exit 1
+        elif [[ "$STATUS" == "OK" ]]; then
           echo "SonarQube Quality Gate passed."
         else
-          echo "SonarQube Quality Gate failed. Stopping CodeBuild..."
+          echo "Unknown SonarQube Quality Gate status: $STATUS"
           exit 1
         fi
 post_build: 
